import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { describe, expect, it } from "vitest";

import {
	buildCollectionPlan,
	collectionConfigPath,
	readCollectionConfig,
} from "../src/collections.js";
import { applyManagedSkillsPlan, buildManagedSkillsPlan } from "../src/managed-skills.js";
import { scanSkills } from "../src/scanner.js";
import { createTempRoot, writeSkill } from "./helpers.js";

import type { SkillCollection } from "../src/types.js";

describe("skill collections", () => {
	it("normalizes and reads collection configuration", async () => {
		const rootPath = await createTempRoot();
		const indexPath = path.join(rootPath, "skill-index");
		await mkdir(indexPath, { recursive: true });
		await writeFile(
			collectionConfigPath(indexPath),
			JSON.stringify({
				version: 1,
				collections: [
					{
						id: "design",
						title: " Design ",
						description: " design tasks. ",
						skillIds: ["visual-review", "ui-polish"],
					},
				],
			}),
			"utf8",
		);

		await expect(readCollectionConfig(indexPath)).resolves.toEqual({
			version: 1,
			collections: [
				{
					id: "design",
					title: "Design",
					description: "Use when design tasks.",
					skillIds: ["ui-polish", "visual-review"],
				},
			],
		});
	});

	it("rejects a collection skill that was not generated by skillzero", async () => {
		const rootPath = await createTempRoot();
		const indexPath = path.join(rootPath, "skill-index");
		const collectionPath = path.join(indexPath, "collections", "design");
		await mkdir(collectionPath, { recursive: true });
		await writeFile(
			collectionConfigPath(indexPath),
			JSON.stringify({
				version: 1,
				collections: [
					{ id: "design", title: "Design", description: "Design tasks.", skillIds: [] },
				],
			}),
			"utf8",
		);
		await writeFile(path.join(collectionPath, "SKILL.md"), "# Manual collection\n", "utf8");

		await expect(scanSkills(rootPath)).rejects.toThrow(
			"Refusing to overwrite non-generated collection skill",
		);
	});

	it("keeps collections while removing deselected skills", async () => {
		const rootPath = await createTempRoot();
		await writeSkill(rootPath, "design-skill", "---\ndescription: Design guidance.\n---\n");
		await writeSkill(rootPath, "api-skill", "---\ndescription: API guidance.\n---\n");

		const indexPath = path.join(rootPath, "skill-index");
		await mkdir(indexPath, { recursive: true });
		const collection: SkillCollection = {
			id: "design",
			title: "Design",
			description: "design tasks.",
			skillIds: ["design-skill"],
		};
		await writeFile(
			collectionConfigPath(indexPath),
			JSON.stringify({ version: 1, collections: [collection] }),
			"utf8",
		);

		const inventory = await scanSkills(rootPath);
		const selectedPlan = await buildManagedSkillsPlan(
			inventory,
			{ indexIds: ["design-skill"], hideIds: [] },
			null,
		);
		expect(selectedPlan.collectionPlan.finalCollections[0]?.skillIds).toEqual(["design-skill"]);

		const restoredPlan = await buildManagedSkillsPlan(
			inventory,
			{ indexIds: [], hideIds: ["design-skill"] },
			null,
		);
		expect(restoredPlan.collectionPlan.finalCollections[0]?.skillIds).toEqual([]);
	});

	it("keeps source paths pointing at the ordinary skill folders", async () => {
		const rootPath = await createTempRoot();
		await writeSkill(rootPath, "design-skill", "---\ndescription: Design guidance.\n---\n");
		const inventory = await scanSkills(rootPath);
		const collection: SkillCollection = {
			id: "design",
			title: "Design",
			description: "tasks related to design.",
			skillIds: ["design-skill"],
		};

		const plan = await buildManagedSkillsPlan(
			inventory,
			{ indexIds: ["design-skill"], hideIds: [] },
			null,
			[collection],
		);
		expect(plan.collectionPlan.collectionSkillFiles[0]?.content).toMatchInlineSnapshot(`
			"---
			name: design
			description: "Use when tasks related to design."
			---
			# Design

			<!-- Generated by skillzero. Do not edit manually. -->

			When a user request matches any of the skill(s), read the source.

			| Skill | Description | Source |
			| --- | --- | --- |
			| \`design-skill\` | Design guidance. | \`../../../design-skill/SKILL.md\` |
			"
		`);
		await applyManagedSkillsPlan(plan);

		const generatedCollection = await readFile(
			path.join(rootPath, "skill-index", "collections", "design", "SKILL.md"),
			"utf8",
		);
		expect(generatedCollection).toContain("../../design-skill/SKILL.md");
		expect(await readFile(path.join(rootPath, "design-skill", "SKILL.md"), "utf8")).toContain(
			"disable-model-invocation: true",
		);
	});
});
