import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { describe, expect, it } from "vitest";

import {
	applyManagedSkillsPlan,
	buildManagedSkillsPlan,
	formatManagedSkillsPlan,
} from "../src/managed-skills.js";
import { scanSkills } from "../src/scanner.js";
import { keepManagedSkills } from "../src/skill-selection.js";
import { readSkillzeroState, skillzeroStatePath } from "../src/state.js";
import { createTempRoot, writeSkill } from "./helpers.js";

import type { SkillCollection } from "../src/types.js";

describe("skill collections", () => {
	it("normalizes collections while reading unified state", async () => {
		const rootPath = await createTempRoot();
		const generatedPath = path.join(rootPath, "skillzero");
		await mkdir(generatedPath, { recursive: true });
		await writeFile(
			skillzeroStatePath(generatedPath),
			JSON.stringify({
				version: 1,
				knownIds: [],
				skills: [],
				collections: [
					{
						id: "design",
						title: " Design ",
						description: " design tasks. ",
						skillIds: ["visual-review", "ui-polish"],
					},
				],
			}),
			"utf8",
		);

		await expect(readSkillzeroState(generatedPath)).resolves.toEqual({
			version: 1,
			knownIds: [],
			skills: [],
			collections: [
				{
					id: "design",
					title: "Design",
					description: "Use when design tasks.",
					skillIds: ["ui-polish", "visual-review"],
				},
			],
		});
	});

	it("rejects a collection skill that was not generated by skillzero", async () => {
		const rootPath = await createTempRoot();
		const generatedPath = path.join(rootPath, "skillzero");
		const collectionPath = path.join(rootPath, "skillzero-design");
		await mkdir(generatedPath, { recursive: true });
		await mkdir(collectionPath, { recursive: true });
		await writeFile(
			skillzeroStatePath(generatedPath),
			JSON.stringify({
				version: 1,
				knownIds: [],
				skills: [],
				collections: [
					{ id: "design", title: "Design", description: "Design tasks.", skillIds: [] },
				],
			}),
			"utf8",
		);
		await writeFile(path.join(collectionPath, "SKILL.md"), "# Manual collection\n", "utf8");

		await expect(scanSkills(rootPath)).rejects.toThrow(
			"Refusing to overwrite non-generated collection skill",
		);
	});

	it("keeps collections while removing skills that become hidden", async () => {
		const rootPath = await createTempRoot();
		await writeSkill(rootPath, "design-skill", "---\ndescription: Design guidance.\n---\n");
		await writeSkill(rootPath, "api-skill", "---\ndescription: API guidance.\n---\n");

		const generatedPath = path.join(rootPath, "skillzero");
		await mkdir(generatedPath, { recursive: true });
		const collection: SkillCollection = {
			id: "design",
			title: "Design",
			description: "design tasks.",
			skillIds: ["design-skill"],
		};
		await writeFile(
			skillzeroStatePath(generatedPath),
			JSON.stringify({
				version: 1,
				knownIds: ["api-skill", "design-skill"],
				skills: [{ id: "design-skill" }],
				collections: [collection],
			}),
			"utf8",
		);

		const inventory = await scanSkills(rootPath);
		const selectedPlan = await buildManagedSkillsPlan(
			inventory,
			["design-skill"],
			inventory.state,
		);
		expect(selectedPlan.collectionPlan.finalCollections[0]?.skillIds).toEqual(["design-skill"]);

		const restoredPlan = await buildManagedSkillsPlan(
			inventory,
			["design-skill"],
			inventory.state,
			[{ ...collection, skillIds: [] }],
		);
		expect(restoredPlan.collectionPlan.finalCollections[0]?.skillIds).toEqual([]);
	});

	it("removes a generated collection when none of its skills remain managed", async () => {
		const rootPath = await createTempRoot();
		await writeSkill(rootPath, "design-skill", "---\ndescription: Design guidance.\n---\n");
		const collection: SkillCollection = {
			id: "design",
			title: "Design",
			description: "design tasks.",
			skillIds: ["design-skill"],
		};

		const initialInventory = await scanSkills(rootPath);
		await applyManagedSkillsPlan(
			await buildManagedSkillsPlan(initialInventory, ["design-skill"], null, [collection]),
		);

		const inventory = await scanSkills(rootPath);
		const collections = keepManagedSkills(inventory.collections, new Set());
		const plan = await buildManagedSkillsPlan(inventory, [], inventory.state, collections);

		expect(collections).toEqual([]);
		expect(plan.collectionPlan.finalCollections).toEqual([]);
		expect(plan.collectionPlan.generatedCollectionIdsToRemove).toEqual(["design"]);
		expect(formatManagedSkillsPlan(plan)).toContain("Remove generated collection: design");
	});

	it("keeps source paths pointing at the ordinary skill folders", async () => {
		const rootPath = await createTempRoot();
		await writeSkill(rootPath, "design-skill", "---\ndescription: Design guidance.\n---\n");
		const inventory = await scanSkills(rootPath);
		const collection: SkillCollection = {
			id: "design",
			title: "Design",
			description: "tasks related to design.",
			skillIds: ["design-skill"],
		};

		const plan = await buildManagedSkillsPlan(
			inventory,
			["design-skill"],
			null,
			[collection],
		);
		expect(plan.collectionPlan.collectionSkillFiles[0]?.content).toMatchInlineSnapshot(`
			"---
			name: design
			description: "Use when tasks related to design."
			---
			# Design

			<!-- Generated by skillzero. Do not edit manually. -->

			When a user request matches any of the skill(s), read the source.

			| Skill | Description | Source |
			| --- | --- | --- |
			| \`design-skill\` | Design guidance. | \`../design-skill/SKILL.md\` |
			"
		`);
		await applyManagedSkillsPlan(plan);

		const generatedCollection = await readFile(
			path.join(rootPath, "skillzero-design", "SKILL.md"),
			"utf8",
		);
		expect(generatedCollection).toContain("../design-skill/SKILL.md");
		expect(await readFile(path.join(rootPath, "design-skill", "SKILL.md"), "utf8")).toContain(
			"disable-model-invocation: true",
		);
	});
});
