import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { describe, expect, it } from "vitest";

import {
  buildCollectionPlan,
  collectionConfigPath,
  generateCollectionSkill,
  readCollectionConfig,
} from "../src/collections.js";
import { applyMovePlan } from "../src/apply.js";
import { applyInPlacePlan, buildInPlacePlan } from "../src/in-place.js";
import { buildMovePlan } from "../src/plan.js";
import { scanSkills } from "../src/scanner.js";
import { createTempRoot, writeSkill } from "./helpers.js";

import type { SkillCollection, SkillRecord } from "../src/types.js";

function managedSkill(rootPath: string, id: string, description: string): SkillRecord {
  const directory = path.join(rootPath, "skill-index", "skills", id);
  return {
    id,
    title: id,
    description,
    disableModelInvocation: false,
    directory,
    skillFile: path.join(directory, "_SKILL.md"),
    origin: "managed",
  };
}

describe("skill collections", () => {
  it("normalizes and reads collection configuration", async () => {
    const rootPath = await createTempRoot();
    const indexPath = path.join(rootPath, "skill-index");
    await mkdir(indexPath, { recursive: true });
    await writeFile(
      collectionConfigPath(indexPath),
      JSON.stringify({
        version: 1,
        collections: [
          {
            id: "design",
            title: " Design ",
            description: " Read for design tasks. ",
            skillIds: ["visual-review", "ui-polish"],
          },
        ],
      }),
      "utf8",
    );

    await expect(readCollectionConfig(indexPath)).resolves.toEqual({
      version: 1,
      collections: [
        {
          id: "design",
          title: "Design",
          description: "Read for design tasks.",
          skillIds: ["ui-polish", "visual-review"],
        },
      ],
    });
  });

  it("rejects a collection skill that was not generated by skillzero", async () => {
    const rootPath = await createTempRoot();
    const indexPath = path.join(rootPath, "skill-index");
    const collectionPath = path.join(indexPath, "collections", "design");
    await mkdir(collectionPath, { recursive: true });
    await writeFile(
      collectionConfigPath(indexPath),
      JSON.stringify({
        version: 1,
        collections: [{ id: "design", title: "Design", description: "Design tasks.", skillIds: [] }],
      }),
      "utf8",
    );
    await writeFile(path.join(collectionPath, "SKILL.md"), "# Manual collection\n", "utf8");

    await expect(scanSkills(rootPath)).rejects.toThrow("Refusing to overwrite non-generated collection skill");
  });

  it("keeps collections while removing skills that are restored to the root", async () => {
    const rootPath = await createTempRoot();
    await writeSkill(rootPath, "design-skill", "---\ndescription: Design guidance.\n---\n");
    await writeSkill(rootPath, "api-skill", "---\ndescription: API guidance.\n---\n");

    const indexPath = path.join(rootPath, "skill-index");
    await mkdir(indexPath, { recursive: true });
    const collection: SkillCollection = {
      id: "design",
      title: "Design",
      description: "Read for design tasks.",
      skillIds: ["design-skill"],
    };
    await writeFile(collectionConfigPath(indexPath), JSON.stringify({ version: 1, collections: [collection] }), "utf8");

    const inventory = await scanSkills(rootPath);
    const selectedPlan = await buildMovePlan(inventory, ["design-skill"]);
    expect(selectedPlan.collectionPlan.finalCollections[0]?.skillIds).toEqual(["design-skill"]);

    const restoredPlan = await buildMovePlan(inventory, []);
    expect(restoredPlan.collectionPlan.finalCollections[0]?.skillIds).toEqual([]);
  });

  it("writes collection routing skills next to the generated index", async () => {
    const rootPath = await createTempRoot();
    await writeSkill(rootPath, "design-skill", "---\ndescription: Design guidance.\n---\n");
    const indexPath = path.join(rootPath, "skill-index");
    await mkdir(indexPath, { recursive: true });
    const collection: SkillCollection = {
      id: "design",
      title: "Design",
      description: "Read for tasks related to design.",
      skillIds: ["design-skill"],
    };
    await writeFile(collectionConfigPath(indexPath), JSON.stringify({ version: 1, collections: [collection] }), "utf8");

    const inventory = await scanSkills(rootPath);
    const plan = await buildMovePlan(inventory, ["design-skill"]);
    await applyMovePlan(plan);

    const generatedCollection = await readFile(path.join(indexPath, "collections", "design", "SKILL.md"), "utf8");
    expect(generatedCollection).toContain("disable-model-invocation: true");
    expect(generatedCollection).toContain("../../skills/design-skill/_SKILL.md");
    await expect(readCollectionConfig(indexPath)).resolves.toEqual({ version: 1, collections: [collection] });
    const refreshedInventory = await scanSkills(rootPath);
    expect(refreshedInventory.collections).toEqual([collection]);
    expect(refreshedInventory.generatedCollectionIds).toEqual(["design"]);
  });

  it("keeps in-place source paths pointing at the ordinary skill folders", async () => {
    const rootPath = await createTempRoot();
    await writeSkill(rootPath, "design-skill", "---\ndescription: Design guidance.\n---\n");
    const inventory = await scanSkills(rootPath);
    const collection: SkillCollection = {
      id: "design",
      title: "Design",
      description: "Read for tasks related to design.",
      skillIds: ["design-skill"],
    };

    const plan = await buildInPlacePlan(inventory, ["design-skill"], null, [collection]);
    await applyInPlacePlan(plan, inventory);

    const generatedCollection = await readFile(
      path.join(rootPath, "skill-index", "collections", "design", "SKILL.md"),
      "utf8",
    );
    expect(generatedCollection).toContain("../../design-skill/SKILL.md");
    expect(await readFile(path.join(rootPath, "design-skill", "SKILL.md"), "utf8")).toContain(
      "disable-model-invocation: true",
    );
  });

  it("generates a collection skill with source metadata", () => {
    const rootPath = "/tmp/project/.codex/skills";
    const indexPath = path.join(rootPath, "skill-index");
    const collection: SkillCollection = {
      id: "design",
      title: "Design",
      description: "Read for tasks related to design.",
      skillIds: ["ui-polish"],
    };

    expect(generateCollectionSkill(collection, [managedSkill(rootPath, "ui-polish", "Improve UI quality.")], indexPath))
      .toMatchInlineSnapshot(`
        "---
        name: design
        description: "Read for tasks related to design."
        disable-model-invocation: true
        ---

        # Design

        <!-- Generated by skillzero. Do not edit manually. -->

        This collection is a routing manifest. When a request matches this collection, read the source \`SKILL.md\` for each relevant skill below before applying it. Source paths are relative to this collection file. This file describes where the skills are; it is not a replacement for their instructions.

        ## Skills

        | Skill | Description | Source |
        | --- | --- | --- |
        | \`ui-polish\` | Improve UI quality. | \`../../skills/ui-polish/_SKILL.md\` |
        "
      `);
  });
});
