import path from "node:path";
import { describe, expect, it } from "vitest";

import { generateIndexSkill } from "../src/index-skill.js";

import type { SkillRecord } from "../src/types.js";

function managedSkill(rootPath: string, id: string, description: string): SkillRecord {
  const directory = path.join(rootPath, "skill-index", "skills", id);
  return {
    id,
    title: id,
    description,
    directory,
    skillFile: path.join(directory, "SKILL.md"),
    origin: "managed",
  };
}

describe("generateIndexSkill", () => {
  it("renders a generated skill with a managed skills table", () => {
    const rootPath = "/tmp/project/.codex/skills";
    const indexPath = path.join(rootPath, "skill-index");
    const content = generateIndexSkill(
      [
        managedSkill(rootPath, "api-builder", "Build | review API contracts."),
        managedSkill(rootPath, "ui-polish", "Improve UI quality."),
      ],
      indexPath,
    );

    expect(content).toMatchInlineSnapshot(`
      "---
      name: skill-index
      description: "Use this skill when a user asks about available skills, wants to use a skill, wants to manage skills, or when a task likely benefits from specialized skill instructions hidden behind this index."
      ---

      # Skill Index

      <!-- Generated by skillzero. Do not edit manually. -->

      Use this skill to decide whether a specialized managed skill should be loaded for the user's request.

      Before applying any managed skill, read the full nested \`SKILL.md\` file listed in the table. Do not rely on this index alone when executing a task.

      ## Managed Skills

      | Skill | Description | Path |
      | --- | --- | --- |
      | \`api-builder\` | Build \\| review API contracts. | \`skills/api-builder/SKILL.md\` |
      | \`ui-polish\` | Improve UI quality. | \`skills/ui-polish/SKILL.md\` |
      "
    `);
  });
});
