import path from "node:path";
import { describe, expect, it } from "vitest";

import { generateIndexSkill } from "../src/index-skill.js";

import type { SkillCollection, SkillRecord } from "../src/types.js";

function managedSkill(rootPath: string, id: string, description: string): SkillRecord {
	const directory = path.join(rootPath, "skill-index", "skills", id);
	return {
		id,
		title: id,
		description,
		disableModelInvocation: false,
		directory,
		skillFile: path.join(directory, "_SKILL.md"),
		origin: "managed",
	};
}

describe("generateIndexSkill", () => {
	it("renders a generated skill with a managed skills table", () => {
		const rootPath = "/tmp/project/.codex/skills";
		const indexPath = path.join(rootPath, "skill-index");
		const content = generateIndexSkill(
			[
				managedSkill(rootPath, "api-builder", "Build | review API contracts."),
				managedSkill(rootPath, "ui-polish", "Improve UI quality."),
			],
			indexPath,
		);

		expect(content).toMatchInlineSnapshot(`
			"---
			name: skill-index
			description: "Use this skill when a user asks about available skills, wants to manage skills or wants to use a skill you don't know."
			---
			# Skill Index

			<!-- Generated by skillzero. Do not edit manually. -->

			When a user request matches any of the skill(s), read the source.

			| Skill | Description | Path |
			| --- | --- | --- |
			| \`api-builder\` | Build \\| review API contracts. | \`skills/api-builder/_SKILL.md\` |
			| \`ui-polish\` | Improve UI quality. | \`skills/ui-polish/_SKILL.md\` |
			"
		`);
	});
});
