import { access, constants, mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { describe, expect, it } from "vitest";

import {
	applyManagedSkillsPlan,
	buildManagedSkillsPlan,
	formatManagedSkillsPlan,
	readManagedSkillsState,
} from "../src/managed-skills.js";
import { scanSkills } from "../src/scanner.js";
import { createTempRoot, writeSkill } from "./helpers.js";

async function exists(filePath: string): Promise<boolean> {
	try {
		await access(filePath, constants.F_OK);
		return true;
	} catch {
		return false;
	}
}

describe("managed skill metadata", () => {
	it("builds stable generated index content for ordinary skill folders", async () => {
		const rootPath = await createTempRoot();
		await writeSkill(
			rootPath,
			"ui-polish",
			'---\ndescription: Improve UI quality.\n---\n',
		);
		await writeSkill(
			rootPath,
			"api-builder",
			'---\ndescription: "Build | review API contracts."\n---\n',
		);

		const inventory = await scanSkills(rootPath);
		const plan = await buildManagedSkillsPlan(
			inventory,
			{ indexIds: ["ui-polish", "api-builder"], hideIds: [] },
			null,
		);

		expect(plan.indexContent).toMatchInlineSnapshot(`
			"---
			name: skill-index
			description: "Use this skill when a user asks about available skills, wants to manage skills or wants to use a skill you don't know."
			---
			# Skill Index

			<!-- Generated by skillzero. Do not edit manually. -->

			When a user request matches any of the skill(s), read the source.

			| Skill | Description | Path |
			| --- | --- | --- |
			| \`api-builder\` | Build \\| review API contracts. | \`../api-builder/SKILL.md\` |
			| \`ui-polish\` | Improve UI quality. | \`../ui-polish/SKILL.md\` |
			"
		`);
	});

	it("applies explicit-only metadata to indexed and hidden skills but only generates indexed rows", async () => {
		const rootPath = await createTempRoot();
		await writeSkill(rootPath, "ui-polish", "---\ndescription: Improve UI quality.\n---\n");
		await writeSkill(rootPath, "private-notes", "---\ndescription: Read private notes.\n---\n");

		const inventory = await scanSkills(rootPath);
		const plan = await buildManagedSkillsPlan(
			inventory,
			{ indexIds: ["ui-polish"], hideIds: ["private-notes"] },
			null,
		);
		expect(plan.finalIndexedSkills.map((skill) => skill.id)).toEqual(["ui-polish"]);
		expect(plan.finalHiddenSkills.map((skill) => skill.id)).toEqual(["private-notes"]);
		expect(plan.operations.map((operation) => operation.label)).toEqual([
			"disable-model-invocation",
			"OpenAI policy",
			"disable-model-invocation",
			"OpenAI policy",
		]);
		await applyManagedSkillsPlan(plan);

		await expect(exists(path.join(rootPath, "ui-polish", "SKILL.md"))).resolves.toBe(true);
		await expect(
			readFile(path.join(rootPath, "ui-polish", "SKILL.md"), "utf8"),
		).resolves.toContain("disable-model-invocation: true");
		await expect(
			readFile(path.join(rootPath, "ui-polish", "agents", "openai.yaml"), "utf8"),
		).resolves.toContain("allow_implicit_invocation: false");
		await expect(
			readFile(path.join(rootPath, "skill-index", "SKILL.md"), "utf8"),
		).resolves.toContain("../ui-polish/SKILL.md");
		await expect(
			readFile(path.join(rootPath, "skill-index", "SKILL.md"), "utf8"),
		).resolves.not.toContain("private-notes");
		await expect(
			readFile(path.join(rootPath, "private-notes", "SKILL.md"), "utf8"),
		).resolves.toContain("disable-model-invocation: true");
		await expect(readManagedSkillsState(await scanSkills(rootPath))).resolves.toMatchObject({
			version: 2,
			knownSkillIds: ["private-notes", "ui-polish"],
			skills: [
				{ id: "private-notes", mode: "hide" },
				{ id: "ui-polish", mode: "index" },
			],
		});

		const refreshedInventory = await scanSkills(rootPath);
		const noOpPlan = await buildManagedSkillsPlan(
			refreshedInventory,
			{ indexIds: ["ui-polish"], hideIds: ["private-notes"] },
			await readManagedSkillsState(refreshedInventory),
		);
		expect(noOpPlan.operations).toEqual([]);
		expect(noOpPlan.indexChanged).toBe(false);
		expect(noOpPlan.collectionPlan.collectionsChanged).toBe(false);
		expect(formatManagedSkillsPlan(noOpPlan)).toContain("No update to 1 indexed skill(s).");
		expect(formatManagedSkillsPlan(noOpPlan)).toContain(
			"Keep 1 skill(s) hidden from generated indexes.",
		);
	});

	it("preserves unrelated Codex metadata and restores the exact original file", async () => {
		const rootPath = await createTempRoot();
		const skillDirectory = await writeSkill(
			rootPath,
			"ui-polish",
			"---\ndescription: Improve UI quality.\n---\n",
		);
		const codexDirectory = path.join(skillDirectory, "agents");
		const codexFile = path.join(codexDirectory, "openai.yaml");
		const originalCodexMetadata = [
			"interface:",
			"  display_name: UI Polish",
			"# Keep this comment.",
			"policy:",
			"  products: [codex]",
			"  allow_implicit_invocation: true # Keep this too.",
			"",
		].join("\n");
		await mkdir(codexDirectory, { recursive: true });
		await writeFile(codexFile, originalCodexMetadata, "utf8");

		const inventory = await scanSkills(rootPath);
		await applyManagedSkillsPlan(
			await buildManagedSkillsPlan(inventory, { indexIds: ["ui-polish"], hideIds: [] }, null),
		);
		const managedMetadata = await readFile(codexFile, "utf8");
		expect(managedMetadata).toContain("display_name: UI Polish");
		expect(managedMetadata).toContain("# Keep this comment.");
		expect(managedMetadata).toContain("allow_implicit_invocation: false # Keep this too.");

		const managedInventory = await scanSkills(rootPath);
		await applyManagedSkillsPlan(
			await buildManagedSkillsPlan(
				managedInventory,
				{ indexIds: [], hideIds: [] },
				await readManagedSkillsState(managedInventory),
			),
		);
		await expect(readFile(codexFile, "utf8")).resolves.toBe(originalCodexMetadata);
	});

	it("does not remove explicit-only policies owned by the skill author", async () => {
		const rootPath = await createTempRoot();
		const skillDirectory = await writeSkill(
			rootPath,
			"manual-only",
			"---\ndescription: Manual only.\ndisable-model-invocation: true\n---\n",
		);
		await mkdir(path.join(skillDirectory, "agents"), { recursive: true });
		await writeFile(
			path.join(skillDirectory, "agents", "openai.yaml"),
			"policy:\n  allow_implicit_invocation: false\n",
			"utf8",
		);

		const inventory = await scanSkills(rootPath);
		await applyManagedSkillsPlan(
			await buildManagedSkillsPlan(inventory, { indexIds: ["manual-only"], hideIds: [] }, null),
		);
		const configured = await scanSkills(rootPath);
		const deselectPlan = await buildManagedSkillsPlan(
			configured,
			{ indexIds: [], hideIds: [] },
			await readManagedSkillsState(configured),
		);
		expect(deselectPlan.operations).toEqual([]);
		await expect(readManagedSkillsState(configured)).resolves.toEqual({
			version: 2,
			knownSkillIds: ["manual-only"],
			skills: [{ id: "manual-only", mode: "index" }],
		});
		await applyManagedSkillsPlan(deselectPlan);

		await expect(readFile(path.join(skillDirectory, "SKILL.md"), "utf8")).resolves.toContain(
			"disable-model-invocation: true",
		);
		await expect(
			readFile(path.join(skillDirectory, "agents", "openai.yaml"), "utf8"),
		).resolves.toContain("allow_implicit_invocation: false");
	});

	it("restores prior false and true policy values when a skill is deselected", async () => {
		const rootPath = await createTempRoot();
		const skillDirectory = await writeSkill(
			rootPath,
			"ui-polish",
			"---\ndisable-model-invocation: false\ndescription: Improve UI quality.\n---\n",
		);
		await mkdir(path.join(skillDirectory, "agents"), { recursive: true });
		await writeFile(
			path.join(skillDirectory, "agents", "openai.yaml"),
			"policy:\n  allow_implicit_invocation: true\n",
			"utf8",
		);

		const inventory = await scanSkills(rootPath);
		await applyManagedSkillsPlan(
			await buildManagedSkillsPlan(inventory, { indexIds: ["ui-polish"], hideIds: [] }, null),
		);
		const configured = await scanSkills(rootPath);
		await applyManagedSkillsPlan(
			await buildManagedSkillsPlan(
				configured,
				{ indexIds: [], hideIds: [] },
				await readManagedSkillsState(configured),
			),
		);

		await expect(readFile(path.join(skillDirectory, "SKILL.md"), "utf8")).resolves.toContain(
			"disable-model-invocation: false",
		);
		await expect(
			readFile(path.join(skillDirectory, "agents", "openai.yaml"), "utf8"),
		).resolves.toContain("allow_implicit_invocation: true");
	});
});
