export const CLI_NAME = "skillzero";
export const CLI_VERSION = "1.0.0";
export const INDEX_SKILL_NAME = "skill-index";
export const MANAGED_SKILLS_DIR_NAME = "skills";
export const COLLECTIONS_DIR_NAME = "collections";
export const COLLECTION_CONFIG_FILE_NAME = "collections.json";
export const SKILL_FILE_NAME = "SKILL.md";
export const MANAGED_SKILL_FILE_NAME = "_SKILL.md";
export const HANDOFF_STATE_FILE_NAME = ".skillzero-handoff.json";
export const IN_PLACE_STATE_FILE_NAME = ".skillzero-in-place.json";
export const KNOWN_SKILLS_STATE_FILE_NAME = ".skillzero-known-skills.json";
export const REDO_STATE_FILE_NAME = ".skillzero-redo.json";
export const DISABLE_MODEL_INVOCATION_FIELD = "disable-model-invocation";
export const GENERATED_MARKER = "<!-- Generated by skillzero. Do not edit manually. -->";

export const INDEX_DESCRIPTION =
	"Use this skill when a user asks about available skills, wants to manage skills or wants to use a skill you don't know.";
