import { readFileSync } from "node:fs";

import { isRecord } from "./values.js";

export const CLI_NAME = "skillzero";

// The package manifest is the release source of truth. Reading it here prevents
// the installed CLI banner and --version output from drifting after a version bump.
const packageManifest: unknown = JSON.parse(
	readFileSync(new URL("../package.json", import.meta.url), "utf8"),
);
if (
	!isRecord(packageManifest) ||
	!("version" in packageManifest) ||
	typeof packageManifest.version !== "string"
) {
	throw new Error("package.json must contain a string version");
}
export const CLI_VERSION = packageManifest.version;
export const GENERATED_DIR_NAME = "skillzero";
export const SKILL_FILE_NAME = "SKILL.md";
export const STATE_FILE_NAME = "state.json";
export const REDO_STATE_FILE_NAME = ".skillzero-redo.json";
export const DISABLE_MODEL_INVOCATION_FIELD = "disable-model-invocation";
export const CODEX_METADATA_DIR_NAME = "agents";
export const CODEX_METADATA_FILE_NAME = "openai.yaml";
export const GENERATED_MARKER = "<!-- Generated by skillzero. Do not edit manually. -->";
