export const CLI_NAME = "skillzero";
export const CLI_VERSION = "1.0.0";
export const INDEX_SKILL_NAME = "skill-index";
export const MANAGED_SKILLS_DIR_NAME = "skills";
export const SKILL_FILE_NAME = "SKILL.md";
export const HANDOFF_STATE_FILE_NAME = ".skillzero-handoff.json";
export const IN_PLACE_STATE_FILE_NAME = ".skillzero-in-place.json";
export const DISABLE_MODEL_INVOCATION_FIELD = "disable-model-invocation";
export const GENERATED_MARKER = "<!-- Generated by skillzero. Do not edit manually. -->";

export const INDEX_DESCRIPTION =
  "Use this skill when a user asks about available skills, wants to use a skill, wants to manage skills, or when a task likely benefits from specialized skill instructions hidden behind this index.";
